"use strict";
exports.__esModule = true;
var Transaction_1 = require("./Transaction");
var BlockChain_1 = require("./BlockChain");
var saneCoin = new BlockChain_1.BlockChain();
var transaction1 = new Transaction_1.Transaction("Sender", "Reciever", 100);
saneCoin.createTransaction(transaction1);
var transaction2 = new Transaction_1.Transaction("Reciever", "Sender", 30);
saneCoin.createTransaction(transaction2);
console.log("mining started");
saneCoin.minePendingTransactions("Miner");
